project:
  type: website
  output-dir: docs
  resources:
    - img/
    - css/
    - slides/
    - schedule/


website:
  title: "Introduction to R for Researchers"
  site-url: https://cstat-msu.github.io/Intro-to-R-4-Researchers/
  google-analytics: G-68JBPLLNLG
  page-footer: >
      This workshop has been developed by members of CSTAT at Michigan State University [CSTAT](https://cstat.msu.edu/)
  
  
  navbar:
    left:
      - text: "Schedule"
        href: schedule/schedule.qmd
    right:
      - text: "CSTAT"
        href: https://cstat.msu.edu/
      - text: "GitHub"
        href: https://github.com/cstat-msu/Intro-to-R-4-Researchers


  
  sidebar:
    title: "Lessons"      # Optional title above the sidebar
    style: "docked"       # Sidebar is docked to the left
    collapse-level: 1     # At what header level to start collapsing
    # contents: auto      # Creates automatic TOC from page headers (no sections)
    contents:
      - section: "Day 1:"
        contents:
          - lessons/01_R-and-RStudio.qmd
          

format:
  html:
    theme: simplex
    css: css/styles.css
    fig-align: "center"
    toc: true
    number-sections: false
    code-block-bg: true
    code-copy: true      # enables copy button (default in most themes)
    code-tools: true     # enables the copy button!
    code-line-wrap: wrap
    prompt: true         
    self-contained: true


# Global Execution Defaults
execute:
  echo: true               # show code
  eval: true               # run code
  warning: false           # show warnings
  error: false             # show errors
  message: false           # show messages
  prompt: true
